### ISSUE TITLE
Cards with grammatically incorrect descriptions

### ISSUE THREAD

**Issue by rhrmo** [vikiival/trap#26]
https://trap.ltd/toxic
Change description to: "Use this card when your opponent uses only toxic and salty arguments"
https://trap.ltd/stupid
Change description to: "Use this card when your opponent thinks you are inferior"
https://trap.ltd/nausea
Change description to: "Use this card when something has made you sick"

**Comment by Hladikes** [comment]
![image](https://user-images.githubusercontent.com/57076047/155134168-56ce6f5d-41d2-42a2-8a15-083504a1bab3.png)

**Comment by vikiival** [comment]
<img src="https://trap.ltd/continue" />
